Revert "[dirmd] Roll dirmd"
This reverts commit 1cf97004ab508e19d04d1efbfd4b8731a1942550.

Reason for revert: roll fails https://crrev.com/c/2915655
Error: dirmd failed.

Original change's description:
> [dirmd] Roll dirmd
>
> Earlier git-ls-files-based optimizations was reverted
> https://chromium-review.googlesource.com/c/chromium/tools/depot_tools/+/2911692.
> Since then the root cause was fixed
> https://chromium-review.googlesource.com/c/chromium/tools/build/+/2911979
> and this CL relands the optimization.
>
> This CL also picks up "mixins" feature which enables reducing duplication of metadata.
> See https://chromium-review.googlesource.com/c/chromium/src/+/2897943
>
> Bug: 1179786, 1201822
> Change-Id: I9697bae9342f6cdc947abe025bebce22b09b530e
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/tools/depot_tools/+/2912261
> Reviewed-by: Prakhar Asthana <pasthana@google.com>
> Commit-Queue: Nodir Turakulov <nodir@chromium.org>

Bug: 1179786
Bug: 1201822
Change-Id: Iea5aad69382da9cfd3e32c74db10721f37aee930
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/tools/depot_tools/+/2909617
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Commit-Queue: Josip Sokcevic <sokcevic@google.com>