[gerrit_util] Add opt-in SSOAuthenticator (reland)
This adds a new authenticator implementation to gerrit_util which
uses the Google corp `git-remote-sso` protocol helper to get
secure tunneled access to the internal hosted Google git services.

It is possible to opt in on Google-managed devices by adding the
following git configuration:

    [url "sso://chromium/"]
        insteadOf = https://chromium.googlesource.com/
        insteadOf = http://chromium.googlesource.com/
    [depot-tools]
      useNewAuthStack = 1

This CL was uploaded using the new authenticator with no
.gitcookies file present on disk.

This was originally landed in
https://chromium-review.googlesource.com/c/chromium/tools/depot_tools/+/5586799

It was reverted because it caused the error:

    AttributeError: module 'functools' has no attribute 'cache'

https://logs.chromium.org/logs/chromium/buildbucket/cr-buildbucket/8745365240091840049/+/u/Commit_log_for_uploaded_revision/stdout

So we changed functools.cache -> functools.lru_cache

Bug: 336351842
Change-Id: I0dcb04ada8281a60792ae08777b01ecf116f2a8f
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/tools/depot_tools/+/5627834
Reviewed-by: Scott Lee <ddoman@chromium.org>
Commit-Queue: Allen Li <ayatane@chromium.org>